apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
    name: github-mcp
    namespace: mcp-servers
spec:
    transportType: "stdio"
    # httpTransport:
    #     targetPort: 8080
    #     path: /
    deployment:
        image: ghcr.io/github/github-mcp-server:latest
        cmd: "/github-mcp-server"
        args: ["stdio"]
        port: 8080
        secretRefs:
            - name: "mcp-servers-env"

# apiVersion: kagent.dev/v1alpha1
# kind: MCPServer
# metadata:
#   creationTimestamp: null
#   name: github-mcp
#   namespace: mcp-servers
# spec:
#   deployment:
#     args:
#     - '@modelcontextprotocol/server-github'
#     cmd: npx
#     port: 3000
#   stdioTransport: {}
#   transportType: stdio
# status: {}
