apiVersion: kagent.dev/v1alpha1
kind: MCPServer
metadata:
    name: github-mcp
    namespace: kmcp-system
spec:
    transportType: "http"
    deployment:
        image: ghcr.io/github/github-mcp-server:latest
        port: 8080
        env:
            - name: GITHUB_TOKEN
              valueFrom:
                  secretKeyRef:
                      name: mcp-servers-env
                      key: GITHUB_TOKEN
