apiVersion: goabout.com/v1beta1
kind: SopsSecretGenerator
metadata:
    name: mcp-servers-env
    disableNameSuffixHash: true
annotations:
    argocd.argoproj.io/hook: "PreSync"
    argocd.argoproj.io/hook-delete-policy: "BeforeHookCreation"
    argocd.argoproj.io/job-cleanup: "keep"
    argocd.argoproj.io/sync-wave: "1"
envs:
    - secrets/confidential/mcp-servers.enc.env
# generatorOptions:
#     disableNameSuffixHash: true
